"use strict";(()=>{var U=Object.defineProperty;var C=Object.getOwnPropertySymbols;var L=Object.prototype.hasOwnProperty,E=Object.prototype.propertyIsEnumerable;var S=(r,e,o)=>e in r?U(r,e,{enumerable:!0,configurable:!0,writable:!0,value:o}):r[e]=o,m=(r,e)=>{for(var o in e||(e={}))L.call(e,o)&&S(r,o,e[o]);if(C)for(var o of C(e))E.call(e,o)&&S(r,o,e[o]);return r};(()=>{let r=(()=>{let t=document.currentScript;if(t&&t.src)return t.src;let n=document.getElementsByTagName("script"),c=n[n.length-1];return c&&c.src?c.src:""})(),e=r?new URL(r,window.location.href).origin:window.location.origin;function o(t){if(t!=null&&t.token)try{fetch(`${e}/api/track`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(t),mode:"cors"}).catch(()=>{})}catch(n){}}let p=(()=>{try{return new URL(document.currentScript&&document.currentScript.src||location.href).origin}catch(t){return location.origin||""}})(),f=document.querySelectorAll(".pm-card");f.length&&f.forEach(async t=>{var b,h,x,v;let n=t.getAttribute("data-slug")||"",c=t.getAttribute("data-pub")||"unknown",y=t.getAttribute("data-article")||"unknown",A=t.getAttribute("data-token")||"";if(!n){t.innerHTML='<div style="font-family:system-ui">Missing data-slug</div>';return}t.innerHTML='<div style="font-family:system-ui">Loading market\u2026</div>';try{let d=await fetch(`${e}/api/gamma/market?slug=${encodeURIComponent(n)}`,{mode:"cors"});if(!d.ok)throw new Error(`HTTP ${d.status}`);let i=await d.json(),w=Array.isArray(i.outcomes)?i.outcomes:JSON.parse(i.outcomes||"[]"),k=Array.isArray(i.outcomePrices)?i.outcomePrices:JSON.parse(i.outcomePrices||"[]"),l=`${e}/trade/${encodeURIComponent(n)}?pub=${encodeURIComponent(c)}&article=${encodeURIComponent(y)}`,$={slug:n,question:i.question||"",pub:c,article:y,token:A,page_url:window.location.href,referrer:document.referrer||""};o(m({event:"impression",ts:Date.now()},$)),t.innerHTML=`
        <div style="font-family:system-ui;max-width:520px;border:1px solid #e5e7eb;border-radius:14px;padding:14px">
          <div style="font-weight:800;margin-bottom:10px">${i.question||n}</div>
          <div style="display:flex;gap:10px;margin:10px 0">
            <button class="pm-go" data-go="${l}" style="flex:1;border:1px solid #e5e7eb;border-radius:12px;padding:10px;background:#fff;text-align:left;cursor:pointer">
              <div style="font-weight:700">${(b=w[0])!=null?b:"YES"}</div>
              <div style="opacity:.7">${(h=k[0])!=null?h:"?"}</div>
            </button>
            <button class="pm-go" data-go="${l}" style="flex:1;border:1px solid #e5e7eb;border-radius:12px;padding:10px;background:#fff;text-align:left;cursor:pointer">
              <div style="font-weight:700">${(x=w[1])!=null?x:"NO"}</div>
              <div style="opacity:.7">${(v=k[1])!=null?v:"?"}</div>
            </button>
          </div>
          <button class="pm-go" data-go="${l}" style="width:100%;border:0;border-radius:12px;padding:10px;background:#111827;color:#fff;font-weight:800;cursor:pointer">
            Trade
          </button>
        </div>
      `,(async()=>{var u;try{if(!p||t.dataset.pmBadged==="1")return;t.dataset.pmBadged="1",t.style.position=t.style.position||"relative";let g=await fetch(p+"/api/embed/meta?slug="+encodeURIComponent(n),{cache:"no-store"});if(!g.ok)return;let s=await g.json().catch(()=>null);if(!s)return;let R=String(((u=s==null?void 0:s.risk)==null?void 0:u.level)||"LOW").toUpperCase(),T=Number((s==null?void 0:s.evidenceCount)||0),a=document.createElement("a");a.href=p+"/risk/"+encodeURIComponent(n),a.target="_blank",a.rel="noreferrer",a.textContent="Risk: "+R+" \xB7 Evidence: "+T,a.style.cssText="position:absolute;top:10px;right:10px;font:800 12px/1 system-ui;padding:6px 10px;border-radius:999px;background:#0b1220;color:#fff;text-decoration:none;opacity:.92;z-index:9999",t.appendChild(a)}catch(g){}})(),t.querySelectorAll(".pm-go").forEach(u=>{u.addEventListener("click",()=>{o(m({event:"click",ts:Date.now()},$)),window.open(u.getAttribute("data-go"),"_blank")})})}catch(d){t.innerHTML='<div style="font-family:system-ui">Couldn\u2019t load this market. Check the slug.</div>',console.error(d)}})})();})();
